//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ProjectManagerEntities : DbContext
{
    public ProjectManagerEntities()
        : base("name=ProjectManagerEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Departments> Departments { get; set; }
    public virtual DbSet<Task_Status> Task_Status { get; set; }
    public virtual DbSet<Tasks> Tasks { get; set; }
    public virtual DbSet<Logins> Logins { get; set; }
}
