'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Departments
    Public Property Department_ID As Integer
    Public Property Department_Name As String

    Public Overridable Property Tasks As ICollection(Of Tasks) = New HashSet(Of Tasks)

End Class
Partial Public Class Task_Status
    Public Property Status_ID As Integer
    Public Property Status_Name As String

    Public Overridable Property Tasks As ICollection(Of Tasks) = New HashSet(Of Tasks)

End Class
Partial Public Class Tasks
    Public Property Task_ID As Integer
    Public Property Task_Name As String
    Public Property Task_Action As String
    Public Property Task_Start As Nullable(Of Date)
    Public Property Task_Deadline As Nullable(Of Date)
    Public Property Task_Staff As String
    Public Property Task_Price As Nullable(Of Decimal)
    Public Property Task_IsPriority As Nullable(Of Boolean)
    Public Property Task_CreationDate As Nullable(Of Date)
    Public Property Task_CompletionDate As Nullable(Of Date)
    Public Property Task_ApprovedDate As Nullable(Of Date)
    Public Property Task_Department As Nullable(Of Integer)
    Public Property Task_Status As Nullable(Of Integer)
    Public Property Task_MainTask As Nullable(Of Integer)

    Public Overridable Property Departments As Departments
    Public Overridable Property Task_Status1 As Task_Status
    Public Overridable Property Tasks1 As ICollection(Of Tasks) = New HashSet(Of Tasks)
    Public Overridable Property Tasks2 As Tasks

End Class
