'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ProjectManagerEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ProjectManagerEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Departments() As DbSet(Of Departments)
    Public Overridable Property Task_Status() As DbSet(Of Task_Status)
    Public Overridable Property Tasks() As DbSet(Of Tasks)

End Class
